### ISSUE TITLE
Sort feature

### ISSUE THREAD

**Issue by red22365-adobe** [krhoton/PotatoShopTestingJS#15]

**Comment by red22365-adobe** [comment]
Hemos vuelto a añadir el issue porque se refiere a ordenar la lista de patatas según el stock, el precio, el nombre..

**Comment by squella** [comment]
@MeritxellRodriguez yo ya he terminado, por tanto, me gustaría ayudarte con esta : ). 
He mirado todas las branch y no he encontrado ninguna con el nombre de **sort**  : /
Quedo la espera de que me digas algo de como fem.
Saludos
